/**
 * deriveFlashcards.js
 *
 * Design decision (documented for the README): flashcards are derived
 * deterministically from the question bank rather than generated by a
 * separate LLM call. Reasons:
 *   1. Keeps front/back consistent with the practice questions instead of
 *      risking a flashcard that contradicts its matching question.
 *   2. One fewer LLM call per requirement -> real savings against a
 *      free-tier token-per-minute limit (Section: "free tiers limit
 *      tokens per minute").
 *   3. It's a pure, testable transform instead of another place invalid
 *      JSON could come back from the model.
 *
 * front is a compressed version of the question prompt; back is the
 * answer_outline. requirement_ids are carried over unchanged, so coverage
 * logic that looks at flashcards stays correct.
 */

function deriveFlashcards(questions) {
  return questions.map((q, i) => ({
    id: `f${i + 1}`,
    front: q.prompt.length > 140 ? `${q.prompt.slice(0, 137)}...` : q.prompt,
    back: q.answer_outline || "(see full answer outline in the question bank)",
    requirement_ids: q.requirement_ids,
  }));
}

module.exports = { deriveFlashcards };
